name = "website"
type = "javascript"
account_id = "068db3d3e9853c780e161269a3233ebf"
workers_dev = true
route = "flick2split.com/*"
main = "./.cloudflare/worker.js"
compatibility_date = "2024-03-12"

[site]
bucket = "dist"
entry-point = "workers-site"


[build]
upload.format = "service-worker" 
command = "npm run build"
